apiVersion: v1
kind: Service
metadata:
  name: tinyllama-service
spec:
  selector:
    app: tinyllama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # Roteia para a porta interna do container
  type: LoadBalancer # Ou ClusterIP, dependendo do seu ambiente